permissions:
  packages: write
  contents: read

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up DevContainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/markhoward02/elexient-com-devcontainer
          imageTag: cache
          cacheFrom: ghcr.io/markhoward02/elexient-com-devcontainer:cache
          runCmd: sh deploy.sh
          push: always

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELEXIENT_COM }}
          channelId: live
          projectId: elexient-com
